-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 31-08-2022 a las 06:35:32
-- Versión del servidor: 10.4.24-MariaDB
-- Versión de PHP: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `principal`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `seguimiento`
--

CREATE TABLE `seguimiento` (
  `accion` text DEFAULT NULL,
  `numero_accion` text DEFAULT NULL,
  `proceso` text DEFAULT NULL,
  `correctiva` text DEFAULT NULL,
  `mejora` text DEFAULT NULL,
  `fecha_definicion` text DEFAULT NULL,
  `fecha_cierre_propuesta` text DEFAULT NULL,
  `fecha_cierre_real` text DEFAULT NULL,
  `eficaz` text DEFAULT NULL,
  `nueva_accion_al_no_ser_eficaz` text DEFAULT NULL,
  `observaciones` text DEFAULT NULL,
  `pendientes` text DEFAULT NULL,
  `hallazgo` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `seguimiento`
--

INSERT INTO `seguimiento` (`accion`, `numero_accion`, `proceso`, `correctiva`, `mejora`, `fecha_definicion`, `fecha_cierre_propuesta`, `fecha_cierre_real`, `eficaz`, `nueva_accion_al_no_ser_eficaz`, `observaciones`, `pendientes`, `hallazgo`) VALUES
('FICHA TECNICA', 'QC-001-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'COORDINADOR DE CALIDAD', '', 'Se  estandarizó  en  la  ficha  técnica  del  producto   INDU010-  BOLSA  D-P  EDEN  DETERGENTE  LIQUIDO  FLORAL  ROPA \nOSCURA  1000ml,  el  uso   de  segunda  mordaza   para  condiciones  de  operación  de la maquina. '),
('MANTENIMIENTO', 'QC-001-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '23/10/2019', 'SI', 'NO', 'COORDINADOR DE PRODUCCION', '', 'Se  Adaptó  una  segunda  mordaza,  con propósito de  realizar  refuerzo en el sellad asegurando  la  eliminación  de  fugas  q afectan la hermeticidad del empaque.'),
('SOCIALIZACION', 'QC-001-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', '', 'PENDIENTE FIRMAS DE SOCIALIZACION', 'Realizar  una  socialización  con  personal  operativo  del  proceso,sobre  la  desviación  reportada y su afectación al cliente en sus  procesos productivos. Este con el propósito \nde  retroalimentar  las  actividades  de  la  operación,  sensibilizar  al  personal  y  contribuir  en  la  toma  de  acciones  correctivas.'),
('IMPLEMENTACION', 'QC-002-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '24/12/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', '', 'Implementar en el proceso de impresión el sistema de comunicación que permita al siguiente operador (operario de revisión) identificar las desviaciones presentadas en el sustrato. Este se realizará a través del uso de etiqueta por sustrato impreso y en él se especificará el nombre de la desviación y su ubicación (según número bandera). '),
('PLAN DE CALIDAD', 'QC-002-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '7/11/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', 'PENDIENTE FIRMAS DE SOCIALIZACION', 'Actualizar y socializar el plan de calidad del proceso de impresión “PR-PL-001”, en el que se especifique el sistema de comunicación establecido para la notificación de las desviaciones presentadas durante la operación de producción y en relación a cada sustrato impreso. '),
('SOCIALIZACION ', 'QC-002-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', 'PENDIENTE FIRMA DE SOCIALIZACION', 'Realizar una socialización con personal operativo del proceso, sobre la desviación reportada y su afectación al cliente en sus procesos productivos. Este con el propósito de retroalimentar las actividades de la operación, sensibilizar al personal y contribuir en la toma de acciones correctivas.'),
('REINDUCCION', 'QC-004-2019', 'CONTROL CALIDAD', 'X', '', '1/07/2019', '1/07/2019', '9/11/2019', 'SI', 'NO', 'CRISTIAN CAMILO SIERRA', 'PENDIENTE FIRMAS DE REINDUCCION', 'Realizar una reinducción al personal del proceso de alistamiento y despacho, con el propósito de fortalecer los conocimientos en el desarrollo de las actividades relacionadas a envíos de producto terminado, teniendo en cuenta los siguientes aspectos:\n1. Condiciones de entrega del producto terminado por parte de producción.\n2. Empaque y embalaje del producto según especificaciones técnicas del cliente.\n3. Identificación del producto, registro en el sistema y emisión de la documentación.\n'),
('REINDUCCION', 'QC-005-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', 'PENDIENTE FIRMA DE REINDUCCION', 'Realizar una reinducción al personal del proceso de corte y refilado, con el propósito de fortalecer los conocimientos del plan de calidad PR-PL-003 y en relación el desarrollo de las actividades de:  banderas y empates, diámetro de bobina y sin anomalías de impresión, teniendo en cuenta los siguientes aspectos:\n1. Cantidad de empates y banderas según especificación del cliente, tolerancias, y metodología de postura. \n2. Diámetros de bobinas, según especificación técnica del cliente y metodología de medición en la línea.\n3.  Visualización de anomalías de impresión y laminación, a través de uso de la lámpara estroboscópica y disminución de velocidades.\n\n'),
('SOCIALIZACION ', 'QC-005-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', 'PENDIENTE FIRMAS DE SOCIALIZACION', 'Realizar una socialización con personal operativo del proceso, sobre la desviación reportada y su afectación al cliente en sus procesos productivos. Este con el propósito de retroalimentar las actividades de la operación, sensibilizar al personal y contribuir en la toma de acciones correctivas.'),
('MANTENIMIENTO', 'QC-006-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Humberto Suárez\n(Gerente de \nProducción)', '', 'Se  realizó  la  fabricación  de    una  paleta  formadora de zipper, con material de alta  resistencia  al  calor,  asegurando  la eliminación  de  transferencia  térmica  en  el  anclaje del zipper al laminado. '),
('REINDUCCION', 'QC-006-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nAseguramiento)', 'PENDIENTE FIRMAS REINDUCCION', 'Realizar  una  reinducción  al  personal  del  proceso  de  sellado,  con  el  propósito  de  fortalecer  los  conocimientos  del  plan  de  calidad PR-PL-004 y en relación el desarrollo \nde  las  actividades  de;  verificación  de  medidas,  verificación  de  anclaje  y  funcionalidad  de  zipper,  teniendo  en  cuenta  los  siguientes  aspectos:\n1.  Medidas;  ancho,  largo,  fuelle  abierto,\nselles,  zipper  (a  borde superior),  muesca  ( a \nborde  superior)perforación  (  a  borde \nsuperior,  según  especificación  del  cliente, \ntolerancias,  y  metodología  de  control. \n2. Metodología de control de funcionalidad \ny anclaje del zipper.'),
('SOCIALIZACION', 'QC-006-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nAseguramiento)', 'PENDIENTES FIRMAS DE SOCIALIZACION', 'Realizar  una  socialización  con  personal  operativo  del proceso,  sobre la desviación  reportada y su afectación al cliente en sus  procesos productivos. Este con el propósito \nde  retroalimentar  las  actividades  de  la  operación,  sensibilizar  al  personal  y  contribuir  en  la  toma  de  acciones  correctivas.'),
('MANTENIMIENTO', 'QC-007-2019', 'CONTROL CALIDAD', 'X', '', '4/12/2019', '4/12/2019', '1/12/2019', 'SI', 'NO', 'Humberto Suarez\n(Coordinador de\nProducción)', '', 'Fabricar los discos formadores del fuelle con  material  teflón,  así  mismo  de    la  estandarización    y  fabricación  de    las  paletas  formadoras, según  las medidas    de  los doy  pack, asegurando  la    estabilidad e  inclinación en el formado'),
('REINDUCCION', 'QC-007-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nAseguramiento)', 'PENDIENTES FIRMA DE REINDUCCION', 'Realizar  una  reinducción  al  personal  del  proceso  de  sellado,  con  el  propósito  de  fortalecer  los  conocimientos  del  plan  de  calidad PR-PL-004 y en relación el desarrollo \nde  las  actividades  de;  verificación  de  hermeticidad,  resistencia  a  impacto  y  compresión  del  empaque,  teniendo  en  cuenta los siguientes aspecto; frecuencias, metodología,  método  de  muestreo,  recursos, estándares y tolerancias.'),
('SOCIALIZACION', 'QC-007-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nAseguramiento)', 'PENDIENTES FIRMAS DE SOCIALIZACION', 'Realizar una socialización con personal operativo del proceso, sobre la desviación reportada y su afectación al cliente en sus procesos productivos. Este con el propósito de retroalimentar las actividades de la operación, sensibilizar al personal y contribuir en la toma de acciones correctivas.'),
('PLAN DE CALIDAD', 'QC-008-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', 'POR EJECUTAR', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nAseguramiento)', 'PENDIENTE REALIZAR PLAN DE CALIDAD PARA LIBERACION DE CAJAS', 'Actualizar y socializar el plan de calidad de liberación de insumos “CC-PL-001”, en el que se especifique el control de las variables y atributos de las “cajas” a través de la definición de responsables, frecuencias, metodología, método de muestreo, recursos, estándares y tolerancias.'),
('REINDUCCION', 'QC-008-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nAseguramiento)', 'PENDIENTES FIRMA DE REINDUCCION', 'Realizar una reinducción al personal del proceso de alistamiento y despacho, con el propósito de fortalecer los conocimientos en el desarrollo de las actividades relacionadas a envíos de producto terminado teniendo en cuenta los siguientes aspectos:\n1. Condiciones de entrega del producto terminado por parte de producción.\n2. Empaque y embalaje del producto según especificaciones técnicas del cliente.\n3. Metodología de acondicionamiento del producto en el embalaje requerido.\n'),
('SOCIALIZACION', 'QC-008-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Brayam Tellez\n(Coordinador de \nDespachos)', 'PENDIENTES FIRMA DE REINDUCCION', 'Implementar en el empaque del producto, el recubrimiento del 100% de la bobina con bolsa en polietileno, para asegurar su inocuidad posterior al envío.'),
('SOCIALIZACION', 'QC-008-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nAseguramiento)', 'PENDIENTES FIRMAS DE SOCIALIZACION', 'Realizar una socialización con personal operativo del proceso, sobre la desviación reportada y su afectación al cliente en sus procesos productivos. Este con el propósito de retroalimentar las actividades de la operación, sensibilizar al personal y contribuir en la toma de acciones correctivas.'),
('PLAN DE CALIDAD', 'QC-009-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '7/11/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', 'PENDIENTES FIRMAS DE SOCIALIZACION', 'Actualizar y socializar el plan de calidad del proceso de sellado “PR-PL-004,”, en el que se especifique la liberación de material de cuadre, ajuste o desviación detectada en los autocontroles” a través de la definición de responsables, frecuencias, metodología, método de muestreo, recursos, estándares y tolerancias.'),
('SOCIALIZACION ', 'QC-009-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', 'PENDIENTES FIRMAS DE SOCIALIZACION', 'Realizar una socialización con personal operativo del proceso, sobre la desviación reportada y su afectación al cliente en sus procesos productivos. Este con el propósito de retroalimentar las actividades de la operación, sensibilizar al personal y contribuir en la toma de acciones correctivas.'),
('MANTENIMIENTO', 'QC-010-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', '', 'Incorporar en el programa de mantenimiento preventivo, el mantenimiento y calibración del rodillo laminador de la máquina laminadora. Esto con el fin de garantizar la puesta a punto del equipo y por consecuente la eliminación de posibles defectos durante proceso.'),
('SOCIALIZACION ', 'QC-010-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', 'PENDIENTES FIRMAS DE SOCIALIZACION', 'Realizar una socialización con personal operativo del proceso, sobre la desviación reportada y su afectación al cliente en sus procesos productivos. Este con el propósito de retroalimentar las actividades de la operación, sensibilizar al personal y contribuir en la toma de acciones correctivas.'),
('MANTENIMIENTO', 'QC-011-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', '', 'Incorporar en el programa de mantenimiento preventivo, el mantenimiento y calibración del rodillo laminador de la máquina laminadora. Esto con el fin de garantizar la puesta a punto del equipo y por consecuente la eliminación de posibles defectos durante proceso.'),
('SOCIALIZACION ', 'QC-011-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo Sierra\n(Coordinador de Aseguramiento)\n', 'PENDIENTES FIRMAS DE SOCIALIZACION', 'Realizar una socialización con personal operativo del proceso, sobre la desviación reportada y su afectación al cliente en sus procesos productivos. Este con el propósito de retroalimentar las actividades de la operación, sensibilizar al personal y contribuir en la toma de acciones correctivas.'),
('FICHA TECNICA', 'QC-012-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nCalidad)', '', 'Se  estandarizó  en  la  ficha  técnica  del  producto  IMBE017-BL  BOLSA D-P INX-80  TRATAMIENTO  CRECE  PELO  X  90  ML,  el  uso   de  segunda  mordaza   para  condiciones  de  operación  de  la  máquina. '),
('MANTENIMIENTO', 'QC-012-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Humberto Suarez\n(Coordinador  de \nProducción)', '', 'Se  Adaptó  una  mordaza,  con  el  propósito  de  realizar  refuerzo  en  el  sellado,  asegurando  la  eliminación  de fugas  que  afectan  la  hermeticidad  del empaque.'),
('SOCIALIZACION', 'QC-012-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nCalidad)', 'PENDIENTE FIRMAS DE SOCIALIZACION', 'Realizar  una  socialización  con  personal  operativo  del  proceso,  sobre  la  desviación reportada y su afectación al  cliente en sus procesos productivos. Este  con  el  propósito  de  retroalimentar  las  actividades de la  operación, sensibilizar  al  personal  y  contribuir  en  la  toma  de  acciones correctivas.'),
('CAPACITACION', 'QC-014-017-2019', 'CONTROL CALIDAD', 'X', 'X', '6/11/2019', '6/11/2019', '6/11/2019', 'SI', 'NO', 'Jefe de Gestión Humana y Jefe HSEQ', '', 'Se evidencia la necesidad de fortalecer los conocimientos del personal involucrado en el proceso, en cuanto a la importancia del coeficiente de fricción, su medición y consecuencias ante posibles desviaciones. Así mismo, las implicaciones en las operaciones de nuestros clientes al recepcionar un material con este tipo de desviación.'),
('PLAN DE CALIDAD', 'QC-014-017-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Jefe HSEQ y Coordinador de Calidad\n', '', 'Actualizar y socializar el plan de calidad del proceso de liberación de materias primas “CC-PL-001”, en donde se especifique el parámetro de verificación al cumplimiento del coeficiente de fricción relacionando frecuencias, metodología, método de muestreo, recursos, estándares y tolerancias.'),
('PLAN DE CALIDAD', 'QC-014-017-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '7/11/2019', 'SI', 'NO', 'Jefe HSEQ y Coordinador de Calidad\n', '', 'Actualizar y socializar el plan de calidad del proceso de sellado “PR-PL-004”, en el que se incluya el control a la variable “apertura de bolsa”, estableciendo frecuencias, metodología, método de muestreo, recursos, estándares y tolerancias.'),
('PLAN DE CALIDAD', 'QC-014-017-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Coordinador de calidad', '', 'Implementar la metodología de Uso del Equipo de Medición “medidor para coeficiente de fricción” para el análisis del parámetro “Coeficiente de fricción”.'),
('PLAN DE CALIDAD', 'QC-014-017-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '7/11/2019', 'SI', 'NO', 'Jefe HSEQ Y Coordinador de Calidad\n', '', 'Actualizar y socializar el plan de calidad del proceso de sellado “PR-PL-004”, especificando la metodología para la liberación de las unidades generadas en el cuadre de máquina.'),
('PROCEDIMIENTO', 'QC-014-017-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Jefe HSEQ y Coordinador de Calidad\n', '', 'En la orden de desarrollo del producto establecer los parámetros relacionados a condiciones de operación en maquina, producto a empacar y sistema de envasado del cliente.'),
('PROCEDIMIENTO', 'QC-014-017-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Jefe HSEQ y Coordinador de Calidad\n', '', 'Incluir en el requerimiento de compra de la materia prima las mezclas parametrizadas según los requerimientos del cliente (condiciones de operación en máquina, tipo de producto a empacar y sistema de envasado).'),
('QUEJA PROVEEDOR', 'QC-018-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '26/12/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nCalidad)', '', 'Al ser una desviación propia de la materia  prima  y  que  debe  ser  garantizada  por  nuestro  proveedor,  se   levanta  la  queja  correspondiente  al  proveedor  y  se  solicita los planes de acción que nos garanticen  la  eliminación de la concurrencia del evento.'),
('MANTENIMIENTO', 'QC-019-2019', 'CONTROL CALIDAD', 'X', '', '16/11/2019', '16/11/2019', '15/11/2019', 'SI', 'NO', 'Gerente de producción\nY Jefe HSEQ\n', '', 'Realizar el cambio de los piñones, correas y rodillos de la maquina selladora 2, con el propósito de generar una mayor tensión en el laminado y así asegurar la eliminación de la variación de este al momento de su troquelado.'),
('PLAN DE CALIDAD', 'QC-019-2019', 'CONTROL CALIDAD', 'X', '', '5/11/2019', '5/11/2019', '7/11/2019', 'SI', 'NO', 'Jefe HSEQ\ny\nCoordinador de Calidad\n', '', 'Actualizar el plan de calidad del proceso de sellado “PR-PL-004”, en el que se incluya el control a la variable “Selle en el círculo de doy pack”, estableciendo frecuencia, metodología, método de muestreo, recursos, estándares y tolerancias.'),
('REINDUCCION', 'QC-019-2019', 'CONTROL CALIDAD', 'X', '', '6/11/2019', '6/11/2019', '7/11/2019', 'SI', 'NO', 'Jefe HSEQ\ny\nCoordinador de Calidad\n', '', 'Realizar una reinducción al personal del proceso de sellado, con el propósito de fortalecer los conocimientos del plan de calidad del mismo “PR-PL-004”, en relación al desarrollo de las actividades y los cambios realizados.'),
('REINDUCCION', 'QC-020-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nCalidad)', 'PENDIENTE FIRMAS', 'Realizar  una  reinducción  al  personal  del  proceso de corte y refilado, con el propósito  de fortalecer los conocimientos del plan de  calidad PR-PL-003 y en relación el desarrollo  de las actividades de: banderas y empates,  diámetro  de  bobina: 1.  Cantidad de empates y banderas según  especificación  del  cliente,  tolerancias,  y \nmetodología  de  postura.  2.  Diámetros  de  bobinas,  según  especificación  técnica  del  cliente  y  metodología de medición en la línea.'),
('SOCIALIZACION', 'QC-020-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '25/10/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nCalidad)', 'PENDIENTES FIRMAS DE SOCIALIZACION', 'Realizar  una  socialización  con  personal  operativo  del proceso,  sobre la desviación  reportada y su afectación al cliente en sus  procesos productivos. Este con  el propósito  de  retroalimentar  las  actividades  de  la  operación,  sensibilizar  al  personal  y  contribuir  en  la  toma  de  acciones  correctivas.'),
('MANTENIMIENTO', 'QC-021-2019', 'CONTROL CALIDAD', 'X', '', '19/12/2018', '19/12/2018', '19/12/2018', 'SI', 'NO', 'Coordinador de \nmantenimiento', '', 'Incorporar en el programa de mantenimiento preventivo,  mantenimiento mecánico de las bombas de la máquina  laminadora, con frecuencia 3 meses”'),
('MANTENIMIENTO', 'QC-021-2019', 'CONTROL CALIDAD', 'X', '', '19/12/2018', '19/12/2018', '19/12/2018', 'SI', 'NO', 'Coordinador de \ncalidad', '', 'Incorporar en el plan de calidad del proceso de  laminación, la prueba “relación de la mezcla”'),
('SOCIALIZACION', 'QC-021-2019', 'CONTROL CALIDAD', 'X', '', '21/12/2018', '21/12/2018', '21/12/2018', 'SI', 'NO', 'Coordinador de \ncalidad', '', 'Realizar socialización de actualización del plan de calidad  con el personal operativo del proceso correspondiente'),
('SOCIALIZACION', 'QC-021-2019', 'CONTROL CALIDAD', 'X', '', '23/01/2019', '23/01/2019', '23/01/2019', 'SI', 'NO', 'Coordinador de \ncalidad', 'PENDIENTES FIRMAS DE SOCIALIZACION', 'Realizar una jornada de socialización y concientización  con el personal del proceso sobre la no conformidad  reportada y su afectación al cliente en sus procesos y  costos.'),
('AUDITORIA', 'QC-022-2019', 'CONTROL CALIDAD', 'X', '', '', '', 'POR EJECUTAR', 'SI', 'NO', 'JEFE HSEQ', 'PENDIENTE DEFINIR FECHA SEGÚN PROGRAMACION DE PROGRAMA DE AUDITORIA.', 'Se  realizará  a  nuestro  proveedor  de  materia  prima,  una  visita  de \nseguimiento,  con el  propósito  de asegurar  el cumplimiento  a  lineamientos \nde las bunas prácticas de fabricación.'),
('BUENAS PRACTICAS DE FABRICACION', 'QC-022-2019', 'CONTROL CALIDAD', 'X', '', '', '3/01/2020', '13/01/2020', 'SI', 'NO', 'JEFE HSEQ', '', 'se  incorporará    en el  chek list   de auditoria   de BPF, \nnuevos  criterios  de  inspección  en  los  procesos  de  producción. '),
('QUEJA PROVEEDOR', 'QC-023-2019', 'CONTROL CALIDAD', 'X', '', '25/10/2019', '25/10/2019', '23/12/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nCalidad)', '', 'Al ser una desviación propia de la materia  prima  y  que  debe  ser  garantizada  por  nuestro  proveedor,  se   levanta  la  queja  correspondiente  al  proveedor  y  se  solicita\nlos planes de acción que nos garanticen  la  eliminación de la concurrencia del evento.'),
('REINDUCCION', 'QC-024-2019', 'CONTROL CALIDAD', 'X', '', '19/11/2019', '19/11/2019', '19/11/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nCalidad)', 'PENDIENTES FIMAS', 'Realizar  una  reinducción  al  personal  del  proceso de alistamiento y despacho, con el  propósito de fortalecer los conocimientos en  el desarrollo de las actividades relacionadas  a  envíos  de  producto  terminado  teniendo  en  cuenta  los  siguientes  aspectos: 1.  Condiciones  de  entrega  del  producto \nterminado  por  parte  de  producción.\n2. Empaque y embalaje del producto según\nespecificaciones  técnicas  del  cliente.\n3. Identificación  del producto, registro en el \nsistema y emisión de la documentación.'),
('PLAN DE CALIDAD', 'QC-025-2019', 'CONTROL CALIDAD', 'X', '', '25/11/2019', '25/11/2019', '7/11/2019', 'SI', 'NO', 'Jefe HSEQ\nY\nCoordinador \nde Calidad', '', 'Actualizar el plan de calidad del proceso de sellado “PRPL-004”, especificando la metodología para la liberación  de las unidades generadas en el cuadre    y/o ajuste  de máquina.'),
('REINDUCCION', 'QC-025-2019', 'CONTROL CALIDAD', 'X', '', '25/11/2019', '25/11/2019', '7/11/2019', 'SI', 'NO', 'Jefe HSEQ\ny\nCoordinador \nde Calidad', '', 'Realizar  una  reinducción  al  personal  del  proceso  de  sellado, con el propósito de fortalecer los conocimientos del plan de calidad  PR-PL-004,  en  relación  el desarrollo \nde las actividades y los cambios realizados'),
('SOCIALIZACION', 'QC-026-2019', 'CONTROL CALIDAD', 'X', '', '25/11/2019', '25/11/2019', '22/11/2019', 'SI', 'NO', 'Cristian Camilo \nSierra\n(Coordinador de \nCalidad)', '', 'Realizar  una  socialización  con  personal  operativo  del proceso,  sobre  la desviación  reportada y su afectación al cliente en sus  procesos  productivos. Este con el propósito \nde  retroalimentar  las  actividades  de  la  operación,  sensibilizar  al  personal  y  contribuir  en  la  toma  de  acciones correctivas.'),
('MANTENIMIENTO', 'QC-026-2019', 'CONTROL CALIDAD', 'X', '', '23/12/2019', '23/12/2019', '23/12/2019', 'SI', 'NO', 'Humberto Suarez\n(Coordinador de \nProducción)', '', 'Se  realiza  adecuación  del  puesto  de  trabajo incorporando  separadores  para los  paquetes que contienen las unidades  y   así mismo  de  la    tolva  para  la  disposición  de  las válvulas.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
